### ISSUE TITLE
Decide on Product MVP

### ISSUE THREAD

**Issue by johnmeade-webdev** [chingu-voyages/v8-bears-team-03#10]
What we gonna make!!??

**Comment by johnmeade-webdev** [comment]
DevBev

MVP
View 1 - Homepage with an RSS style feed 
View 2 - Form page to add a post

**Comment by ghost** [comment]
2 views: 
Homepage with public feed
Can filter homepage by drink category

Submission page to add a post to the public feed
form should have specific options depending on the drink category selected

database:
mongodb for persisting data
models for beer, coffee, tea, liquor

api
flesh out all the end points needed
front page will need a get and delete method
submission page is going to need a post method
